#!/bin/sh

PREREQ="console_setup brltty"
prereqs() { echo "$PREREQ"; }

case "$1" in
        prereqs)
        prereqs
        exit 0
        ;;
esac

if [ -x /usr/bin/setleds ] ; then
	INITTY=/dev/tty[1-8]
	for tty in $INITTY ; do
		setleds -D +num < $tty
	done
fi

exit 0

