name: Release

on:
  release:
    types: [published]

jobs:
  extract-tag:
    name: Extract release tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.RELEASE_TAG }}
      version: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Parse refs
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/*/}
          RELEASE_VERSION=$(echo "$RELEASE_TAG" | sed 's/^[^0-9]*//')
          echo "Detected version: $RELEASE_VERSION; Tag: $RELEASE_TAG"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

pkg-deb:
  name: Package for Debian
  needs: ["extract-tag"]
  runs-on: ubuntu-latest
  steps:
    - name: Create package file
      run: |
        dpkg-deb -v --build ./debian
        mv debian.deb initrams-numlock-on-${{ needs.extract-tag.outputs.version }}.deb
    - name: Upload .deb tools package
      run: gh release upload ${{ needs.extract-tag.outputs.tag }} initrams-numlock-on-${{ needs.extract-tag.outputs.version }}.deb
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
